2023-09-07 21:40:26,859 - myapp - DEBUG - Starting the application
2023-09-07 21:40:26,860 - myapp - INFO - Doing something...
2023-09-07 21:40:26,860 - myapp - ERROR - An error occurred: division by zero
Traceback (most recent call last):
  File "d:\End to End\Test.py", line 18, in do_something
    result = 10 / 0
ZeroDivisionError: division by zero
2023-09-07 21:40:26,860 - myapp - DEBUG - Application finished
2023-09-07 21:40:33,071 - myapp - DEBUG - Starting the application
2023-09-07 21:40:33,071 - myapp - INFO - Doing something...
2023-09-07 21:40:33,071 - myapp - ERROR - An error occurred: division by zero
Traceback (most recent call last):
  File "d:\End to End\Test.py", line 18, in do_something
    result = 10 / 0
ZeroDivisionError: division by zero
2023-09-07 21:40:33,076 - myapp - DEBUG - Application finished
